// src/spa/meps-content-creation/src/shell/TopBar.tsx
import React from "react";
import { useAuth } from "react-oidc-context";
import {
  Home,
  ChevronDown,
  Search,
  Bell,
  HelpCircle,
  User,
  LayoutGrid,
  LogOut,
  Check,
} from "lucide-react";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { workspaceLinks, navItems } from "../data/workspaces";

const SHELL_HOME_URL = "http://localhost:3000";

const TopBar: React.FC = () => {
  const auth = useAuth();

  return (
    <header className="bg-white border-b border-gray-300 flex items-center h-11">
      {/* Left section: MEPS logo + workspace dropdown + nav items */}
      <div className="flex items-center h-full">
        {/* MEPS Logo */}
        <a
          href={SHELL_HOME_URL}
          className="flex items-center gap-1 px-3 text-gray-700 font-bold text-sm border-r border-gray-300 h-full hover:bg-gray-50"
        >
          MEPS
        </a>

        {/* Workspace icon + dropdown */}
        <WorkspaceDropdown />

        {/* Nav items: Publications, Workflow */}
        {navItems.map((item) => (
          <DropdownMenu.Root key={item.id}>
            <DropdownMenu.Trigger asChild>
              <button className="flex items-center gap-1 px-3 h-full text-sm text-gray-700 hover:bg-gray-100 transition-colors border-r border-gray-200">
                {item.label}
                <ChevronDown size={12} className="text-gray-400" />
              </button>
            </DropdownMenu.Trigger>
            <DropdownMenu.Portal>
              <DropdownMenu.Content
                className="bg-white rounded-md shadow-lg border border-gray-200 p-2 min-w-[160px] z-50"
                sideOffset={2}
              >
                <DropdownMenu.Item className="px-3 py-2 text-sm text-gray-500 outline-none">
                  {item.label} menu — coming soon
                </DropdownMenu.Item>
              </DropdownMenu.Content>
            </DropdownMenu.Portal>
          </DropdownMenu.Root>
        ))}
      </div>

      {/* Right section: icons */}
      <div className="flex items-center gap-1 ml-auto pr-3">
        <button className="p-2 text-gray-500 hover:text-meps-blue" aria-label="Search">
          <Search size={18} />
        </button>
        <button className="p-2 text-gray-500 hover:text-meps-blue relative" aria-label="Notifications">
          <Bell size={18} />
          <span className="absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full" />
        </button>
        <button className="p-2 text-gray-500 hover:text-meps-blue" aria-label="Help">
          <HelpCircle size={18} />
        </button>

        {/* User menu */}
        <DropdownMenu.Root>
          <DropdownMenu.Trigger asChild>
            <button className="p-2 text-gray-500 hover:text-meps-blue" aria-label="User menu">
              <User size={18} />
            </button>
          </DropdownMenu.Trigger>
          <DropdownMenu.Portal>
            <DropdownMenu.Content
              className="bg-white rounded-md shadow-lg border border-gray-200 p-2 min-w-[180px] z-50"
              sideOffset={5}
              align="end"
            >
              <DropdownMenu.Label className="px-2 py-1 text-sm text-gray-500">
                {auth.user?.profile?.email}
              </DropdownMenu.Label>
              <DropdownMenu.Separator className="h-px bg-gray-200 my-1" />
              <DropdownMenu.Item
                className="flex items-center gap-2 px-2 py-2 text-sm text-gray-700 rounded cursor-pointer hover:bg-gray-100 outline-none"
                onSelect={() => auth.signoutRedirect()}
              >
                <LogOut size={14} />
                Sign out
              </DropdownMenu.Item>
            </DropdownMenu.Content>
          </DropdownMenu.Portal>
        </DropdownMenu.Root>

        <button className="p-2 text-gray-500 hover:text-meps-blue" aria-label="Grid view">
          <LayoutGrid size={18} />
        </button>
      </div>
    </header>
  );
};

/** Workspace icon button with dropdown showing workspace list */
const WorkspaceDropdown: React.FC = () => {
  return (
    <DropdownMenu.Root>
      <DropdownMenu.Trigger asChild>
        <button className="flex items-center gap-1 px-3 h-11 text-gray-600 hover:bg-gray-100 transition-colors border-r border-gray-200">
          <span className="text-lg">✏️</span>
          <ChevronDown size={12} className="text-gray-400" />
        </button>
      </DropdownMenu.Trigger>
      <DropdownMenu.Portal>
        <DropdownMenu.Content
          className="bg-white rounded-md shadow-lg border border-gray-200 py-2 min-w-[220px] z-50"
          sideOffset={2}
          align="start"
        >
          {/* MEPS Home link */}
          <DropdownMenu.Item
            className="flex items-center gap-3 px-4 py-2 text-sm text-meps-blue cursor-pointer hover:bg-gray-50 outline-none"
            onSelect={() => { window.location.href = "http://localhost:3000"; }}
          >
            <Home size={16} />
            MEPS Home
          </DropdownMenu.Item>

          <DropdownMenu.Separator className="h-px bg-gray-200 my-1" />

          {/* Workspaces label */}
          <DropdownMenu.Label className="px-4 py-1 text-xs font-semibold text-gray-500 uppercase tracking-wide">
            Workspaces
          </DropdownMenu.Label>

          {/* Workspace items */}
          {workspaceLinks.map((ws) => (
            <DropdownMenu.Item
              key={ws.id}
              className={`flex items-center gap-3 px-4 py-2 text-sm cursor-pointer outline-none ${
                ws.active
                  ? "text-gray-800 font-medium"
                  : "text-gray-600 hover:bg-meps-blue hover:text-white"
              }`}
              onSelect={() => {
                if (!ws.active) window.location.href = ws.href;
              }}
            >
              <span className="text-base">{ws.icon}</span>
              <span className="flex-1">{ws.label}</span>
              {ws.active && <Check size={14} className="text-gray-500" />}
            </DropdownMenu.Item>
          ))}
        </DropdownMenu.Content>
      </DropdownMenu.Portal>
    </DropdownMenu.Root>
  );
};

export default TopBar;

// src/spa/meps-translation/src/shell/TopBar.vue
<template>
  <header class="bg-white border-b border-gray-300 flex items-center h-11">
    <!-- Left section -->
    <div class="flex items-center h-full">
      <!-- MEPS Logo -->
      <a href="http://localhost:3000"
         class="flex items-center gap-1 px-3 text-gray-700 font-bold text-sm border-r border-gray-300 h-full hover:bg-gray-50">
        MEPS
      </a>

      <!-- Workspace icon -->
      <button class="flex items-center gap-1 px-3 h-full text-gray-600 hover:bg-gray-100 border-r border-gray-200">
        <span class="text-lg">🔤</span>
        <svg class="w-3 h-3 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
        </svg>
      </button>

      <!-- Nav items -->
      <button v-for="item in navItems" :key="item.id"
              :class="['flex items-center gap-1 px-3 h-full text-sm transition-colors border-r border-gray-200',
                        item.active ? 'bg-gray-200 font-semibold text-gray-800' : 'text-gray-700 hover:bg-gray-100']">
        {{ item.label }}
        <svg v-if="item.hasDropdown" class="w-3 h-3 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
        </svg>
      </button>
    </div>

    <!-- Right section -->
    <div class="flex items-center gap-1 ml-auto pr-3">
      <button class="p-2 text-gray-500 hover:text-blue-800" aria-label="Search">
        <svg class="w-[18px] h-[18px]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
        </svg>
      </button>
      <button class="p-2 text-gray-500 hover:text-blue-800 relative" aria-label="Notifications">
        <svg class="w-[18px] h-[18px]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"/>
        </svg>
        <span class="absolute top-1 right-1 w-4 h-4 bg-red-500 rounded-full text-white text-[9px] flex items-center justify-center font-bold">3</span>
      </button>
      <button class="p-2 text-gray-500 hover:text-blue-800" aria-label="Help">
        <svg class="w-[18px] h-[18px]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
        </svg>
      </button>
      <button class="p-2 text-gray-500 hover:text-blue-800" aria-label="User" @click="$emit('sign-out')">
        <svg class="w-[18px] h-[18px]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/>
        </svg>
      </button>
      <button class="p-2 text-gray-500 hover:text-blue-800" aria-label="Settings">
        <svg class="w-[18px] h-[18px]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.066 2.573c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.573 1.066c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.066-2.573c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/>
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
        </svg>
      </button>
      <button class="p-2 text-gray-500 hover:text-blue-800" aria-label="Grid view">
        <svg class="w-[18px] h-[18px]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"/>
        </svg>
      </button>
    </div>
  </header>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "TopBar",
  emits: ["sign-out"],
  setup() {
    const navItems = [
      { id: "dashboard", label: "Dashboard", active: true, hasDropdown: false },
      { id: "personnel", label: "Personnel", active: false, hasDropdown: true },
      { id: "media", label: "Media", active: false, hasDropdown: true },
      { id: "projects", label: "Projects", active: false, hasDropdown: true },
      { id: "library", label: "Library", active: false, hasDropdown: true },
      { id: "publish", label: "Publish", active: false, hasDropdown: true },
    ];

    return { navItems };
  },
});
</script>
